DO $$
BEGIN
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'personas') THEN
	CREATE TABLE PERSONAS
	(
		PER_CODIGO SERIAL,
        PER_NOMBRES VARCHAR(45) NOT NULL,
        PER_APELLIDOS VARCHAR(45) NOT NULL,
		CONSTRAINT PK_PERSONAS PRIMARY KEY(PER_CODIGO)
	);
	RAISE NOTICE 'SE HA CREADO LA TABLA PERSONAS';
END IF;
END $$;