DO $$
BEGIN
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'usuarios') THEN
	CREATE TABLE USUARIOS
	(
		USU_CODIGO SERIAL,
		PER_CODIGO INT NOT NULL,
		USU_USUARIO VARCHAR(45) NOT NULL,
        USU_CLAVE VARCHAR(45) NOT NULL,
		CONSTRAINT PK_USUARIOS PRIMARY KEY(USU_CODIGO),
		CONSTRAINT FK_USUARIOS_PERSONAS FOREIGN KEY (PER_CODIGO) REFERENCES PERSONAS (PER_CODIGO)
	);
	RAISE NOTICE 'SE HA CREADO LA TABLA USUARIOS';
END IF;
END $$;