DO $$
BEGIN
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'productos') THEN
	CREATE TABLE PRODUCTOS
	(
		PRO_REFERENCIA VARCHAR(45) NOT NULL,
        PRO_DESCRIPCION VARCHAR(45) NOT NULL,
        PRO_VALOR NUMERIC(12, 2) NOT NULL,
		CONSTRAINT PK_PRODUCTOS PRIMARY KEY(PRO_REFERENCIA)
	);
	RAISE NOTICE 'SE HA CREADO LA TABLA PRODUCTOS';
END IF;
END $$;