DO $$
BEGIN
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'carros') THEN
	CREATE TABLE CARROS
	(
		CAR_CODIGO SERIAL,
		PRO_REFERENCIA VARCHAR(45) NOT NULL,
		USU_CODIGO INT NOT NULL,
        CAR_CANTIDAD INT NOT NULL,
        CAR_TOTAL NUMERIC(12, 2) NOT NULL,
        CAR_ESTADO INT NOT NULL,
		CONSTRAINT PK_CARROS PRIMARY KEY(CAR_CODIGO),
		CONSTRAINT FK_CARROS_PRODUCTOS FOREIGN KEY (PRO_REFERENCIA) REFERENCES PRODUCTOS (PRO_REFERENCIA),
        CONSTRAINT FK_CARROS_USUARIOS FOREIGN KEY (USU_CODIGO) REFERENCES USUARIOS (USU_CODIGO)
	);
	RAISE NOTICE 'SE HA CREADO LA TABLA CARROS';
END IF;
END $$;